server.port=8080

# PostgreSQL (Guilda) Config
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Elasticsearch Config
spring.elasticsearch.uris=http://localhost:9200

# Redis Config (TP3)
spring.redis.host=${REDIS_HOST:localhost}
spring.redis.port=6379

# MongoDB Config (TP3)
spring.data.mongodb.uri=mongodb://${MONGO_HOST:localhost}:27017/guilda_logs

# Actuator Config (TP6)
management.endpoints.web.exposure.include=health,info,env,metrics
management.endpoint.health.show-details=always

# Logging / Debug para Autoconfig (TP3) 
# logging.level.org.springframework.boot.autoconfigure=DEBUG
# security log 
logging.level.org.springframework.security=INFO

# Spring Security Defaults
app.security.admin.user=admin
app.security.admin.pass=admin123
app.security.user.user=user
app.security.user.pass=user123
